// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mesh/membership_designator.go

// Package mock_mesh is a generated GoMock package.
package mock_mesh

import (
	context "context"
	reflect "reflect"

	v1beta2 "github.com/aws/aws-app-mesh-controller-for-k8s/apis/appmesh/v1beta2"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockMembershipDesignator is a mock of MembershipDesignator interface.
type MockMembershipDesignator struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipDesignatorMockRecorder
}

// MockMembershipDesignatorMockRecorder is the mock recorder for MockMembershipDesignator.
type MockMembershipDesignatorMockRecorder struct {
	mock *MockMembershipDesignator
}

// NewMockMembershipDesignator creates a new mock instance.
func NewMockMembershipDesignator(ctrl *gomock.Controller) *MockMembershipDesignator {
	mock := &MockMembershipDesignator{ctrl: ctrl}
	mock.recorder = &MockMembershipDesignatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipDesignator) EXPECT() *MockMembershipDesignatorMockRecorder {
	return m.recorder
}

// Designate mocks base method.
func (m *MockMembershipDesignator) Designate(ctx context.Context, obj v1.Object) (*v1beta2.Mesh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Designate", ctx, obj)
	ret0, _ := ret[0].(*v1beta2.Mesh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Designate indicates an expected call of Designate.
func (mr *MockMembershipDesignatorMockRecorder) Designate(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Designate", reflect.TypeOf((*MockMembershipDesignator)(nil).Designate), ctx, obj)
}
