
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-gatewayroute
  failurePolicy: Fail
  name: mgatewayroute.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - gatewayroutes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-mesh
  failurePolicy: Fail
  name: mmesh.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - meshes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-virtualgateway
  failurePolicy: Fail
  name: mvirtualgateway.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualgateways
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-virtualnode
  failurePolicy: Fail
  name: mvirtualnode.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualnodes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-virtualrouter
  failurePolicy: Fail
  name: mvirtualrouter.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualrouters
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-appmesh-k8s-aws-v1beta2-virtualservice
  failurePolicy: Fail
  name: mvirtualservice.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualservices
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.appmesh.k8s.aws
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-gatewayroute
  failurePolicy: Fail
  name: vgatewayroute.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - gatewayroutes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-mesh
  failurePolicy: Fail
  name: vmesh.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - meshes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-virtualgateway
  failurePolicy: Fail
  name: vvirtualgateway.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualgateways
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-virtualnode
  failurePolicy: Fail
  name: vvirtualnode.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualnodes
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-virtualrouter
  failurePolicy: Fail
  name: vvirtualrouter.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualrouters
  sideEffects: None
- clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appmesh-k8s-aws-v1beta2-virtualservice
  failurePolicy: Fail
  name: vvirtualservice.appmesh.k8s.aws
  rules:
  - apiGroups:
    - appmesh.k8s.aws
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualservices
  sideEffects: None
