# permissions for end users to edit backendgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendgroup-editor-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups/status
  verbs:
  - get
