# permissions for end users to view backendgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendgroup-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups/status
  verbs:
  - get
