# permissions for end users to view gatewayroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayroute-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - gatewayroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - gatewayroutes/status
  verbs:
  - get
