---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups
  - gatewayroutes
  - meshes
  - virtualgateways
  - virtualnodes
  - virtualrouters
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - backendgroups/status
  - gatewayroutes/status
  - meshes/status
  - virtualgateways/status
  - virtualnodes/status
  - virtualrouters/status
  - virtualservices/status
  verbs:
  - get
  - patch
  - update
