# permissions for end users to edit virtualgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualgateway-editor-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualgateways/status
  verbs:
  - get
