# permissions for end users to view virtualgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualgateway-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualgateways/status
  verbs:
  - get
