// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/webhook/validator.go

// Package mock_webhook is a generated GoMock package.
package mock_webhook

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
	admission "sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Prototype mocks base method.
func (m *MockValidator) Prototype(req admission.Request) (runtime.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prototype", req)
	ret0, _ := ret[0].(runtime.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prototype indicates an expected call of Prototype.
func (mr *MockValidatorMockRecorder) Prototype(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prototype", reflect.TypeOf((*MockValidator)(nil).Prototype), req)
}

// ValidateCreate mocks base method.
func (m *MockValidator) ValidateCreate(ctx context.Context, obj runtime.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreate", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCreate indicates an expected call of ValidateCreate.
func (mr *MockValidatorMockRecorder) ValidateCreate(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreate", reflect.TypeOf((*MockValidator)(nil).ValidateCreate), ctx, obj)
}

// ValidateDelete mocks base method.
func (m *MockValidator) ValidateDelete(ctx context.Context, obj runtime.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDelete", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateDelete indicates an expected call of ValidateDelete.
func (mr *MockValidatorMockRecorder) ValidateDelete(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDelete", reflect.TypeOf((*MockValidator)(nil).ValidateDelete), ctx, obj)
}

// ValidateUpdate mocks base method.
func (m *MockValidator) ValidateUpdate(ctx context.Context, obj, oldObj runtime.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUpdate", ctx, obj, oldObj)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUpdate indicates an expected call of ValidateUpdate.
func (mr *MockValidatorMockRecorder) ValidateUpdate(ctx, obj, oldObj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUpdate", reflect.TypeOf((*MockValidator)(nil).ValidateUpdate), ctx, obj, oldObj)
}
