apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.appmesh.k8s.aws
spec:
  group: appmesh.k8s.aws
  versions:
    - name: v1alpha1
      served: true
      storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    plural: virtualservices
    singular: virtualservice
    kind: VirtualService
    categories:
      - all
      - appmesh
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          properties:
            meshName:
              type: string
            virtualRouter:
              type: object
              properties:
                name:
                  type: string
            routes:
              type: array
              properties:
                items:
                  type: object
                  properties:
                    http:
                      type: object
                      properties:
                        match:
                          type: object
                          properties:
                            prefix:
                              type: string
                        action:
                          type: object
                          properties:
                            weightedTargets:
                              type: array
                              properties:
                                items:
                                  type: object
                                  properties:
                                    virtualNodeName:
                                      type: string
                                    weight:
                                      type: integer
        status:
          properties:
            virtualServiceArn:
              type: string
            virtualRouterArn:
              type: string
            routeArns:
              type: array
              items:
                type: string
            conditions:
              type: array
              properties:
                items:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      enum:
                        - Active
                    status:
                      type: string
                      enum:
                        - True
                        - False
                        - Unknown
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string