name: "Run Integration Test"
description: "Runs integration tests in a kinD cluster on a github action"

inputs:
  aws_role:
    description: "role to acquire from aws"
    required: true
  vpc_id:
    description: "aws vpc id to use for the test"
    required: true
  account_id:
    description: "aws account id to use"
    required: true
  cluster_name:
    description: "name of the test cluster"
    required: false
    default: "test-cluster"

runs:
  using: "composite"
  steps:
    - name: Install Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: '1.17.*'
      id: go

    - name: Setup Test Tools
      shell: bash
      run: |
        export GOBIN=/usr/local/bin/

        mkdir -vp ~/.docker/cli-plugins/
        curl -sL -o ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64"
        chmod a+x ~/.docker/cli-plugins/docker-buildx

        curl -L -o kubebuilder.tar.gz "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz"
        tar xzf kubebuilder.tar.gz
        sudo mv "kubebuilder_2.3.1_linux_amd64" /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin

        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

        ./scripts/install-controller-gen.sh
        ./scripts/install-kubectl.sh
        go install sigs.k8s.io/kustomize/kustomize/v4@latest

        go mod download
        go install github.com/onsi/ginkgo/ginkgo@v2.9.2

    - name: Run Unit Tests
      shell: bash
      run: |
        make test

    - name: Configure AWS Credentials (build)
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-west-2
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: IntegrationTest

    - name: Setup Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"
        name: "${{ inputs.cluster_name }}"

    - name: Run Integration Tests
      shell: bash
      env:
        VPC_ID: "${{ inputs.vpc_id }}"
        AWS_ACCOUNT_ID: "${{ inputs.account_id }}"
        CLUSTER_NAME: "${{ inputs.cluster_name }}"
      run: |
        KUBECONFIG="${HOME}/.kube/config" ./scripts/test-with-kind.sh
