// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/aws/aws-app-mesh-controller-for-k8s/pkg/apis/appmesh/v1beta1"
	"github.com/aws/aws-app-mesh-controller-for-k8s/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AppmeshV1beta1Interface interface {
	RESTClient() rest.Interface
	MeshesGetter
	VirtualNodesGetter
	VirtualServicesGetter
}

// AppmeshV1beta1Client is used to interact with features provided by the appmesh.k8s.aws group.
type AppmeshV1beta1Client struct {
	restClient rest.Interface
}

func (c *AppmeshV1beta1Client) Meshes() MeshInterface {
	return newMeshes(c)
}

func (c *AppmeshV1beta1Client) VirtualNodes(namespace string) VirtualNodeInterface {
	return newVirtualNodes(c, namespace)
}

func (c *AppmeshV1beta1Client) VirtualServices(namespace string) VirtualServiceInterface {
	return newVirtualServices(c, namespace)
}

// NewForConfig creates a new AppmeshV1beta1Client for the given config.
func NewForConfig(c *rest.Config) (*AppmeshV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AppmeshV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new AppmeshV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AppmeshV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AppmeshV1beta1Client for the given RESTClient.
func New(c rest.Interface) *AppmeshV1beta1Client {
	return &AppmeshV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AppmeshV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
