// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-app-mesh-controller-for-k8s/pkg/virtualgateway (interfaces: MembershipDesignator)

// Package mock_virtualgateway is a generated GoMock package.
package mock_virtualgateway

import (
	context "context"
	v1beta2 "github.com/aws/aws-app-mesh-controller-for-k8s/apis/appmesh/v1beta2"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	reflect "reflect"
)

// MockMembershipDesignator is a mock of MembershipDesignator interface
type MockMembershipDesignator struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipDesignatorMockRecorder
}

// MockMembershipDesignatorMockRecorder is the mock recorder for MockMembershipDesignator
type MockMembershipDesignatorMockRecorder struct {
	mock *MockMembershipDesignator
}

// NewMockMembershipDesignator creates a new mock instance
func NewMockMembershipDesignator(ctrl *gomock.Controller) *MockMembershipDesignator {
	mock := &MockMembershipDesignator{ctrl: ctrl}
	mock.recorder = &MockMembershipDesignatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMembershipDesignator) EXPECT() *MockMembershipDesignatorMockRecorder {
	return m.recorder
}

// DesignateForGatewayRoute mocks base method
func (m *MockMembershipDesignator) DesignateForGatewayRoute(arg0 context.Context, arg1 *v1beta2.GatewayRoute) (*v1beta2.VirtualGateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DesignateForGatewayRoute", arg0, arg1)
	ret0, _ := ret[0].(*v1beta2.VirtualGateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DesignateForGatewayRoute indicates an expected call of DesignateForGatewayRoute
func (mr *MockMembershipDesignatorMockRecorder) DesignateForGatewayRoute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DesignateForGatewayRoute", reflect.TypeOf((*MockMembershipDesignator)(nil).DesignateForGatewayRoute), arg0, arg1)
}

// DesignateForPod mocks base method
func (m *MockMembershipDesignator) DesignateForPod(arg0 context.Context, arg1 *v1.Pod) (*v1beta2.VirtualGateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DesignateForPod", arg0, arg1)
	ret0, _ := ret[0].(*v1beta2.VirtualGateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DesignateForPod indicates an expected call of DesignateForPod
func (mr *MockMembershipDesignatorMockRecorder) DesignateForPod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DesignateForPod", reflect.TypeOf((*MockMembershipDesignator)(nil).DesignateForPod), arg0, arg1)
}
