// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/virtualgateway/membership_designator.go

// Package mock_virtualgateway is a generated GoMock package.
package mock_virtualgateway

import (
	context "context"
	reflect "reflect"

	v1beta2 "github.com/aws/aws-app-mesh-controller-for-k8s/apis/appmesh/v1beta2"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockMembershipDesignator is a mock of MembershipDesignator interface.
type MockMembershipDesignator struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipDesignatorMockRecorder
}

// MockMembershipDesignatorMockRecorder is the mock recorder for MockMembershipDesignator.
type MockMembershipDesignatorMockRecorder struct {
	mock *MockMembershipDesignator
}

// NewMockMembershipDesignator creates a new mock instance.
func NewMockMembershipDesignator(ctrl *gomock.Controller) *MockMembershipDesignator {
	mock := &MockMembershipDesignator{ctrl: ctrl}
	mock.recorder = &MockMembershipDesignatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipDesignator) EXPECT() *MockMembershipDesignatorMockRecorder {
	return m.recorder
}

// DesignateForGatewayRoute mocks base method.
func (m *MockMembershipDesignator) DesignateForGatewayRoute(ctx context.Context, obj *v1beta2.GatewayRoute) (*v1beta2.VirtualGateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DesignateForGatewayRoute", ctx, obj)
	ret0, _ := ret[0].(*v1beta2.VirtualGateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DesignateForGatewayRoute indicates an expected call of DesignateForGatewayRoute.
func (mr *MockMembershipDesignatorMockRecorder) DesignateForGatewayRoute(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DesignateForGatewayRoute", reflect.TypeOf((*MockMembershipDesignator)(nil).DesignateForGatewayRoute), ctx, obj)
}

// DesignateForPod mocks base method.
func (m *MockMembershipDesignator) DesignateForPod(ctx context.Context, pod *v1.Pod) (*v1beta2.VirtualGateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DesignateForPod", ctx, pod)
	ret0, _ := ret[0].(*v1beta2.VirtualGateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DesignateForPod indicates an expected call of DesignateForPod.
func (mr *MockMembershipDesignatorMockRecorder) DesignateForPod(ctx, pod interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DesignateForPod", reflect.TypeOf((*MockMembershipDesignator)(nil).DesignateForPod), ctx, pod)
}
